### ISSUE TITLE
[ARIFA] Mendix - Acompañamiento - Pase Interno al Equipo (10/abr)

### ISSUE THREAD

**Issue by apicardami** [ubiqua/ARIFA#53]
## JTBD
- [ARIFA] Mendix - Acompañamiento - Pase Interno al Equipo

## Objetivo del Cliente
¿Que espera o desea el cliente?
- [ ] "Puesta en Produccion" => Lanzar el primer modulo en vivo a sus usuarios internos.

## Resultados Claves
Para lograrlo, el cliente tiene que llevar a cabo un proceso de "puesta en produccion"; que incluye: 

1. Definir el modelo de "Deployment / Infraestructura".
2. Aprovisionar un "Firewall or proxy server"
3. Aprovisionar un "Webserver o Application Server"
4. Aprovisionar un "Database Server"
5. Aprovisionar un "File Server"
6. Preparar cada "servidor". 
7. Instalar el entorno de "Mendix"
8. Desplegar un "Mendix App".

## Avances a la Fecha
A lo largo de 3 talleres, logramos el siguiente avance: 
- [X] Preparacion: Definir el Modelo de "[Deployment / Infraestructura](https://github.com/ubiqua/ARIFA/issues/27#issue-2157506818)".
- [x] Preparacion: Preparar un [Checklist de Instalacion](https://docs.google.com/spreadsheets/d/1cD6mlrkQorgvJeIGLiThKna2EY8ekdQ2oRFay-DBZp8/edit#gid=699983453)
- [x] Infraestructura: [Aprovisionar Webserver](https://github.com/ubiqua/ARIFA/issues/27#issuecomment-1967528521)
- [x] Infraestructura: [Aprovisionar Database Server](https://github.com/ubiqua/ARIFA/issues/27#issuecomment-1967530918)
- [x] Instalacion: [Prerequisitos de Sistema Operativo](https://github.com/ubiqua/ARIFA/issues/28#issuecomment-1969802477)
- [x] Instalacion: [Instalar the Mendix Service Console ](https://github.com/ubiqua/ARIFA/issues/31#issuecomment-1973803577)
- [x] Instalacion: [Preparar y compartir un MPK y App Package](https://github.com/ubiqua/ARIFA/issues/31#issuecomment-1973816920)
- [x] Instalacion: [Deploy a Mendix Application](https://github.com/ubiqua/ARIFA/issues/31#issuecomment-1973829631)

![image](https://github.com/ubiqua/ARIFA/assets/8126769/88eb13da-881b-4340-904a-1ec9f0b54d1b)

## Plan de Accion a Seguir
¿Que queda pendiente por completar? => "Completar el proceso de Instalacion"
- [ ] Instalacion: [Configuring Microsoft IIS Server](https://docs.google.com/spreadsheets/d/1cD6mlrkQorgvJeIGLiThKna2EY8ekdQ2oRFay-DBZp8/edit#gid=699983453)
- [ ] Instalacion: [Activate a Mendix License on Microsoft Windows](https://docs.google.com/spreadsheets/d/1cD6mlrkQorgvJeIGLiThKna2EY8ekdQ2oRFay-DBZp8/edit#gid=699983453)
- [ ] Instalacion: [MS Windows: Update a Mendix App](https://docs.google.com/spreadsheets/d/1cD6mlrkQorgvJeIGLiThKna2EY8ekdQ2oRFay-DBZp8/edit#gid=699983453)
- [ ] Instalacion: [Security for Your On-Premises Installation](https://docs.google.com/spreadsheets/d/1cD6mlrkQorgvJeIGLiThKna2EY8ekdQ2oRFay-DBZp8/edit#gid=699983453)
- [ ] Instalacion: [File Server](https://github.com/ubiqua/ARIFA/issues/29)
- [ ] Instalacion: [Firewall or Proxy Server](https://github.com/ubiqua/ARIFA/issues/30)
- [ ] Activar Usuario, Prueba, Ajuste, Validar que todo funciona..

## Roles y Responsables
¿Que rol jugará cada persona?
- Encargado tecnico, Sergio
- Coordinacion con el cliente, Nicole
- Apoyo a Sergio y Nicole, Diego y Alberto

Los contactos de parte del cliente son: 
- Abraham Castillo, acastillo@arifa.com, Director de Tecnologia
- Gabriel Moreno, gmoreno@arifa.com

## Siguientes Pasos
- [ ] Sergio, preparacion tecnica. Leer el material y estar listo para ser el consultor ante el cliente.
- [ ] Nicole, coordinacion. Contactar al cliente para coordinar los espacios de trabajo.
- [ ] Alberto, estaré presente en la 1ra sesion, para presentarlos y de ahi que puedan trabajar directamente con el cliente.

## Referencias, Trabajo Previo
- https://github.com/ubiqua/ARIFA/issues/27
- https://github.com/ubiqua/ARIFA/issues/28
- https://github.com/ubiqua/ARIFA/issues/31

## Referencias, Documentacion Tecnica
- https://github.com/ubiqua/ARIFA/milestone/2
- https://github.com/ubiqua/ARIFA/issues/24
- https://github.com/ubiqua/ARIFA/issues/25
- https://github.com/ubiqua/ARIFA/issues/3
- https://github.com/ubiqua/ARIFA/issues/31

**Comment by apicardami** [comment]
![image](https://github.com/ubiqua/ARIFA/assets/8126769/a965f414-f5cc-433a-ac34-4993b2dec3b4)
